name: CI/CD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-account-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Install the dependencies
        working-directory: account-service
        run: npm install
      - name: Launch the service
        working-directory: account-service
        run: |
          npm start &
          PID="$( echo $! )"
          sleep 5
          curl -sL "http://localhost:5050/"
          kill "$PID"
