name: CI/CD
on:
  push: # Every time a new commit is pushed
    branches-ignore: # Except on branches with the following names (bots)
      - 'renovate/**'
      - 'dependabot/**'
    paths-ignore: # Or if the commit is only related to these files
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      - '.gitignore'
  pull_request: # Always run if there is a pull request
  workflow_dispatch: # Enable launching the pipeline from the web interface

jobs:

  Build-Backend:
    runs-on: ubuntu-latest # Pick a Linux machine
    steps:
      - name: Checkout the repository
        # There is a ready-to-use action for that!
        uses: actions/checkout@v3.0.2
      - name: Read the version of Python
        # We need an id for the step, as we will use its outpot later on
        id: python-version
        # I couldn't find a ready-to-use action, so let's write the necessary steps
        # The will be executed on the selected shell
        shell: bash
        # Similar to "cd backend", runs the commands inside that folder
        working-directory: backend
        # Read the file and set its content as output of this step
        run: echo "::set-output name=version::$(cat .python-version)"
      - name: Install Python
        # There is a ready-to-use action for that!
        uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{ steps.python-version.outputs.version }}
      - name: Install Poetry
        # There is a ready-to-use action for that!
        uses: snok/install-poetry@v1.3.1
      - name: Install dependencies
        shell: bash
        working-directory: backend
        # Let's set the environment variable used by Flask App
        run: poetry install
      - name: Run unit tests
        shell: bash
        working-directory: backend
        run: poetry run pytest
      - name: Run the end to end test
        shell: bash
        working-directory: backend
        run: ./end-to-end-test.sh

  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Install all dependencies
        working-directory: frontend
        run: npm install
      - name: Run the tests
        shell: bash
        working-directory: frontend
        run: npm test -- --watchAll=false

  Build-Agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Just skip, as there are no agents yet
        run: true

  Integration-Testing:
    needs:
      - Build-Backend
      - Build-Frontend
      - Build-Agents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Containerize the backend
        run: docker build -t escooter-backend backend
      - name: Prepare the frontend
        working-directory: frontend
        run: npm install
      - name: Containerize the agents
        run: true # no agents yet
      - name: Run the integration test
        run: true # Start the backend, start the agents, perform an interaction

  Deploy:
    needs:
      - Integration-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Containerize the backend
        run: docker build -t ghcr.io/danysk/dtm-se-escooter-example-backend:latest backend
      - name: Login to the container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Deliver backend on registry
        run: docker push ghcr.io/danysk/dtm-se-escooter-example-backend:latest
